### PR TITLE
jackson 2.9.10

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by arthurdm** [comment]
thanks @sullis - can you please follow the link under the ECA failure to complete that part of the process?

**Comment by sullis** [comment]
LGTM @EricWittmann

**Comment by arthurdm** [comment]
thx @sullis

**Pull request merged**
