### PR TITLE
#216 - Add example to content

### PR DESCRIPTION
**Pull request by ivanjunckes**
Signed-off-by: ivanjunckes <ijunckes@tomitribe.com>

### CODE REVIEW

**Comment by EricWittmann** [comment]
Great, thanks for opening a new PR, Ivan!  So now the only question I have is whether the TCK should have a separate test for `example` or whether sharing it with `examples` is OK.

What do you think, @arthurdm ?

**Comment by arthurdm** [comment]
thanks @ivanjunckes !     I agree with @EricWittmann - maybe you can simply change the value of the singular example to something like `jsmith`?   Just so that we can ensure the singular and plural examples aren't overriding each other.

**Comment by EricWittmann** [comment]
I actually meant that I think we need a TCK test where `@Content` doesn't contain **both** the `example` and `examples` properties.  Since it's an OAI spec violation to use both properties in the same `Content` element.

My suggestion is to either add another method to the JAX-RS resource, or find an `@Content` annotation that doesn't have an example defined.

**Comment by arthurdm** [comment]
good point @EricWittmann - I had forgotten about that restriction.

**Comment by ivanjunckes** [comment]
Cool I will fix that.

**Comment by ivanjunckes** [comment]
Fixed, I removed one of the "examples" that were not being used anywhere in the TCK, and used it to test "example". I hope this is ok.

**Comment by arthurdm** [comment]
thanks @ivanjunckes!

**Pull request merged**
