### PR TITLE
Change methods to access Operations in PathItems

### PR DESCRIPTION
**Pull request by jmini**
See original discussion in issue #234 (point `1.`)

I was surprised to not find any tests for the model in the TCK.

I understand that it focus on App-Server stuff (equivalent of ` 	swagger-jaxrs2`) but you have a set of constraints on the model interfaces as well.

For example, With:

```
PathItem p;
Operation o;
```

You can do:
```java
p.readOperationsMap().put(HttpMethod.POST, o);
```
Or:
```
p.setPOST(o);
```

Does the API tells if they are equivalent or not?

If you take the swagger-core implementation it is not. 
`readOperationsMap()` is somehow a view map (it should be unmodifiable in my opinion, this is an other story).

On the other side, doing this on the Kaizen model seems to update the the POST operation.

I think that going over the setter should be the recommended way.
Forcing the `getOperations()` to be unmodifiable is a to restrictive, but allowing modification is also a problem for implementation that do not keep the information inside a Map.

### CODE REVIEW

**Comment by arthurdm** [comment]
thanks @jmini.  Have you looked at this TCK test? https://github.com/eclipse/microprofile-open-api/blob/master/tck/src/main/java/org/eclipse/microprofile/openapi/tck/ModelConstructionTest.java   It tests the methods of the model classes.

I agree about the lack of description on how these methods interact.  I think that making the methods that return a map as immutable is a good idea.  I will open an issue for it.

**Comment by jmini** [comment]
@arthurdm: I do not see any `readOperationsMap()` call in `ModelConstructionTest.java`.

**Comment by jmini** [comment]
I have added some tests to `pathItemTest()`. Please review them carefully, because it is the first time I write some TCK tests.

2 questions:

* Should the deprecated methods provide a default implementation that delegates to `getOperations()`?
* Should my TCK tests also test the deprecated method?

**Comment by arthurdm** [comment]
I don't think it's necessary to test or add default impls for the deprecated methods.

**Comment by jmini** [comment]
I think I have updated the test as you have suggested.

**Comment by arthurdm** [comment]
looks great, thanks @jmini!

**Comment by jmini** [comment]
I had an additional idea: why not provide a default implementation for the 2 olds methods? See #243.

**Pull request merged**
