### PR TITLE
Fix incorrect return/setter types

### PR DESCRIPTION
**Pull request by arturdzm**
- Fix parameter examples to be consistent with other annotations (Content, Components)
- Fix Encoding model to use already defined enum for the style

### CODE REVIEW

**Comment by arthurdm** [comment]
looks good @arturdzm - can you please make the corresponding change to the TCK app(s)?

**Comment by InhexSTER** [comment]
@arthurdm sure, done

**Comment by arturdzm** [comment]
@arthurdm added new commit for tck

**Comment by arthurdm** [comment]
thanks @arturdzm, looks good.

**Pull request merged**
