### PR TITLE
Add PathItem#setOperation(HttpMethod, Operation)

### LINKED ISSUE #432: Add setOperation(HttpMethod, Operation) on PathItem
When `PathItem#getOperations()` you have a `Map<HttpMethod, Operation>`. If you are looping over the entries, you would like to be able to set the `Operation` on the `PathItem` based on the key.

Example usage: with `pathItem` and `otherPathItem` two `PathItem` instances:

```java
Map<HttpMethod, Operation> operations = pathItem.getOperations();
for (Entry<HttpMethod, Operation> entry : operations.entrySet()) {
    HttpMethod httpMethod = entry.getKey();
    Operation operation = createModifiedCopy(entry.getValue());
    otherPathItem.setOperation(httpMethod, operation);
}
```

### PR DESCRIPTION
**Pull request by jmini**
Fixes #432

### CODE REVIEW

**Comment by MikeEdgar** [comment]
+1

Thoughts on adding an associated accessor/getter?

**Comment by jmini** [comment]
> Thoughts on adding an associated accessor/getter?

We already have following methods on `PathItem`:

* `getGET()`
* `getPOST()`
* `getPUT()`
* `getDELETE()`
* ...

So `getOperation(HttpMethod.GET)` would be the same as `getGET()` and so on?

As explained in #432, the goal of the proposed `PathItem#setOperation(HttpMethod, Operation)` in this PR is to be a contra-part of `PathItem#getOperations()` (when you iterate over the entries of this map).

**Comment by MikeEdgar** [comment]
@jmini - I see your point. I was thinking that the `Map` returned by `getOperations` might be mutable (the JavaDoc is silent about its mutability, unlike other `Map`s in the API).

**Comment by jmini** [comment]
Any opinion if this can be merged for `2.0` ?

**Comment by MikeEdgar** [comment]
I am not opposed to including this with `2.0`.

**Pull request merged**
