### PR TITLE
Change the pom.xml versions to 1.0.1-SNAPSHOT to prepare for a 1.0.1 release

### PR DESCRIPTION
**Pull request by EricWittmann**
This is a simple pom.xml change for the version number.  I don't know if it's required prior to releasing 1.0.1 but it seemed sensible.

Signed-off-by: Eric Wittmann <eric.wittmann@gmail.com>

### CODE REVIEW

**Comment by arthurdm** [comment]
Thanks @EricWittmann - I wonder though, if we should let the release build take care of these changes, so that it properly matches the changes it will do afterwards.  For example, check out these changes from `metrics` when they did a `1.0.1` release: https://github.com/eclipse/microprofile-metrics/commit/32f1a722f5e3f69930da1a4f11b77b8bae1cac45#diff-600376dffeb79835ede4a0b285078036

The `genie-microprofile` account is used by the release build.

**Comment by EricWittmann** [comment]
Yeah ok that's fine with me.  As I said, I wasn't sure if this would be necessary or not.  Happy to let the release process take care of things if that's the procedure. :)

**Comment by arthurdm** [comment]
Cool - thanks @EricWittmann 

I will be kicking off the release build sometime this week, so if it all goes well I will close this PR.  Will leave it open in case I need it afterall =)

**Comment by EricWittmann** [comment]
OK sounds good, thanks @arthurdm.

**Comment by arthurdm** [comment]
Release `1.0.1` is out the door.  I noticed that the automated Jenkins tool left the versions at `1.0.2`, so if you wanted to update this PR to move those into `1.1` we could merge it. =)

**Comment by EricWittmann** [comment]
Oh I don't know - that seems like a lot of work........ ;)

**Comment by EricWittmann** [comment]
OK done - you can resolve conflicts directly in GitHub now.  Super cool.

**Pull request merged**
