### PR TITLE
Allow APIResponse on resource class

### LINKED ISSUE #417: APIResponse and APIResponses should target TYPE as well
Currently APIResponse and APIResponses use:
`@Target({ ElementType.METHOD })`

The Swagger equivalent handles this differently (see
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/responses/ApiResponses.java):
`@Target({METHOD, TYPE, ANNOTATION_TYPE})`

This makes it possible to add a response to **all** `@Operation`s in a class. It would be great if this was possible with MP OpenAPI as well!

### PR DESCRIPTION
**Pull request by Azquelt**
`APIResponse` annotations on the method override `APIResponse` annotations
on the resource class with the same response code.

Fixes #417

### CODE REVIEW

**Comment by Azquelt** [comment]
Reading over this again, should we allow `@APIResponse` to be applied to an `ExceptionMapper` class as well as the `toResponse` method?

Adding it to the class seems more natural, I assume it was only applied to the method because previously the annotation only targeted methods.

**Comment by MikeEdgar** [comment]
> Reading over this again, should we allow @APIResponse to be applied to an ExceptionMapper class as well as the toResponse method?

I think that makes sense.

**Comment by Azquelt** [comment]
Updated to test for APIResponse on an ExceptionMapper class.

**Review by MikeEdgar — APPROVED** [review]
Looks good, thank you.

**Pull request merged**
