### PR TITLE
Updates to the TCK for changes to Parameter and Schema interfaces.

### PR DESCRIPTION
**Pull request by mrglavas**
Signed-off-by: Michael Glavassevich <mrglavas@ca.ibm.com>

### CODE REVIEW

**Comment by mrglavas** [comment]
This PR also includes changes to ensure that the tests run in the container instead of as a client. See @Deployment method.

**Comment by mrglavas** [comment]
I removed tests for Schema sub-types in anticipation of those interfaces being removed from the API.

**Comment by mrglavas** [comment]
@arturdzm See TCK changes here for Schema.

**Comment by arthurdm** [comment]
thanks Michael! looks good.

**Pull request merged**
