### PR TITLE
Adding SPI for platform APIs

### LINKED ISSUE #212: Investigate the addition of an SPI
The MP OpenAPI spec specifies how to fetch the OpenAPI v3 doc for a single application at `/openapi`.  However, the application server that runs this applications likely has other RESTful APIs that it wants to expose - not from applications, but from the server itself.  Examples include other MicroProfile specs, such as `/health` and `/metrics`, as well as other potential endpoints such as an OpenID Connect endpoint at `/oidc` to manage tokens.

This workitem explores the idea of an SPI that allows vendors to provide OpenAPI v3 definition for these extra "management" side APIs.  

Rough proposal:
(1)  a new Java interface (SPI), where 0..N providers inside the application server can implement:
```
interface OpenAPIProvider
   String getContextRoot()
   String getOpenAPI()
```

(2) a new endpoint, `openapi/providers` which returns a list of currently registered OpenAPIProvider's context roots.

(3) For each `{provider}` in (2), a new URL `openapi/providers/{provider}`.

-----  Example -----

If we have (2) return:
```
'providers':
- metrics
- health
- oidc
```

Then we would have these URLs available in (3):
`openapi/providers/metrics`
`openapi/providers/health`
`openapi/providers/oidc`

### PR DESCRIPTION
**Pull request by arthurdm**
Fixes #212 

Adding new SPI for platform OpenAPIs.

### CODE REVIEW

**Comment by jmini** [comment]
I am really not in the application server business, but the feature seems reasonable to me...

---

In regard to the other discussion about YAML vs JSON, can the client send an Header `Content-Type: application/json` during the `GET /openapi/platform` call to get the list of component in JSON format?

---

For the embedded platform OpenAPI specs like `GET /openapi/platform/metrics`, what will be their OpenAPI "header", in particular the `servers` bloc? I guess it should be the url of the running server? The `info` block might be dynamic as well...

---

I was also wondering if a merged OpenAPI-spec of all endpoints is desirable or not.

---

While I was reading the document I was telling to myself that the endpoints available under `/openapi/*` could be described as an OpenAPI spec. It would be somehow complementary to the text specification.

**Comment by arthurdm** [comment]
@EricWittmann - any comments on this PR?

**Comment by EricWittmann** [comment]
I'll have a look as soon as I can carve out a bit of time.  Should be today.

Question: this seems like a pretty big addition to the spec for 1.1, especially at this stage.  Perhaps we should defer this to 2.0?

**Comment by arthurdm** [comment]
that's a good point @EricWittmann - I wanted to release `RC1` for `1.1` today and the thought about this SPI being deferred for `2.0` crossed my mind as well.

I guess `1.1` would be then focused on the addition of `PATCH` and all the annotation / model improvements / fixes, which sounds reasonable to me.

**Comment by arthurdm** [comment]
re-targeted to `2.0`

**Comment by EricWittmann** [comment]
+1 - and sorry I didn't get a chance to review this on Friday. :(

**Pull request merged**
