### PR TITLE
Make ModelConstructionTest run within the container

### PR DESCRIPTION
**Pull request by arturdzm**
When running with the container, this test validates that all model classes are accessible from within the application's context (for filter, etc)

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by arthurdm** [comment]
sounds good @EricWittmann - please let us know.

**Comment by jmini** [comment]
My use case is to use the interfaces defined in `org.eclipse.microprofile.openapi.models.*` to work with an OpenAPI model, independently from any server or container. 
I have open-sourced a bridge that wraps Swagger-Core into the interfaces and I plan to contribute something similar for KaiZen (see [empoa](https://openapitools.github.io/empoa/))

I know that this is not the primary target of MicroProfile which is a set of spec that comes on top of Ja(va|karta)EE (and on top of JaxRS in the particular case of OpenAPI).

In addition I do not know Arquillian well, but I had the feeling that the ModelConstructionTest do not requires a container.

If you put this back in (reverting https://github.com/eclipse/microprofile-open-api/commit/9e8d57a4b27241cf9b243990fa57be3c8cf306bc), this forces a container to be present. Can I run the tests without any container? If yes how?

See #270 and #274

**Comment by EricWittmann** [comment]
By the way - I think this PR needs to be submitted against the `1.x` branch.  Or when merged it should be cherry-picked.  My last PR was done against `1.x` and I presume our release this week would be done against that branch.  Not sure how you want to handle this, @arthurdm

**Comment by arthurdm** [comment]
good point @EricWittmann.

hey @arturdzm - can we please re-target to the `1.x` branch?  Shouldn't hit any merging errors.

**Comment by EricWittmann** [comment]
@arthurdm @arturdzm - this looks good to me once it's retargetted to the `1.x` branch.  I've tested this with both SmallRye and Thorntail and both now pass the TCK.  So a big +1 from me.

**Pull request merged**
