### PR TITLE
<fix>(417): Changed applicable context for ApiResponse and ApiResponses annotations

### LINKED ISSUE #417: APIResponse and APIResponses should target TYPE as well
Currently APIResponse and APIResponses use:
`@Target({ ElementType.METHOD })`

The Swagger equivalent handles this differently (see
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/responses/ApiResponses.java):
`@Target({METHOD, TYPE, ANNOTATION_TYPE})`

This makes it possible to add a response to **all** `@Operation`s in a class. It would be great if this was possible with MP OpenAPI as well!

### PR DESCRIPTION
**Pull request by Name-not-available**
I really want this to be done in order to highly decrease amount of boilerplate in my project.

Fixes #417.

Thank you.

### CODE REVIEW

**Comment by nikita-kuklin** [comment]
Will this be merged after legal agreement signment?

**Comment by Emily-Jiang** [comment]
> Will this be merged after legal agreement signment?

TCKs for this need to be added as well.

**Comment by MikeEdgar** [comment]
@Name-not-available are you interested in picking this back up? I think it might be good to limit this change to just adding `ElementType.TYPE`. We could revisit adding `ElementType.ANNOTATION_TYPE` in the future when that can be added consistently to any other annotations necessary in this project. 

If you'd like to work this one, please take a look at updating the TCK so that (1) at least one of the test resources has an `@APIResponse` at the class level and (2) the tests are updated to check that the response is applied to the operations contained in the resource class. Of course you'll need to complete the necessary legal agreement as well.

**Comment by MikeEdgar** [comment]
Replaced by #524

**Pull request closed without merging**
